// <auto-generated />
using System;
using DiyetisyenProje.PL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiyetisyenProje.PL.Migrations
{
    [DbContext(typeof(DiyetDbContext))]
    [Migration("20230106161253_ilk")]
    partial class ilk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DiyetisyenProje.PL.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adminler");
                });

            modelBuilder.Entity("DiyetisyenProje.PL.Entities.Besin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<int>("BesinKategoriId")
                        .HasColumnType("int");

                    b.Property<double>("Kalori")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BesinKategoriId");

                    b.ToTable("Besinler");
                });

            modelBuilder.Entity("DiyetisyenProje.PL.Entities.BesinKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BesinKategoriler");
                });

            modelBuilder.Entity("DiyetisyenProje.PL.Entities.BitenListe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("ListeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("ListeId");

                    b.ToTable("BitenListeler");
                });

            modelBuilder.Entity("DiyetisyenProje.PL.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BelCevresi")
                        .HasColumnType("float");

                    b.Property<double>("Boy")
                        .HasColumnType("float");

                    b.Property<double>("BoyunCevresi")
                        .HasColumnType("float");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("KalcaCevresi")
                        .HasColumnType("float");

                    b.Property<double>("Kilo")
                        .HasColumnType("float");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListeId")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("DiyetisyenProje.PL.Entities.Liste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("ListeAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Listeler");
                });

            modelBuilder.Entity("DiyetisyenProje.PL.Entities.ListeBesin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BesinId")
                        .HasColumnType("int");

                    b.Property<int>("ListeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BesinId");

                    b.HasIndex("ListeId");

                    b.ToTable("ListeBesinler");
                });

            modelBuilder.Entity("DiyetisyenProje.PL.Entities.Besin", b =>
                {
                    b.HasOne("DiyetisyenProje.PL.Entities.BesinKategori", "BesinKategori")
                        .WithMany("Besinler")
                        .HasForeignKey("BesinKategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BesinKategori");
                });

            modelBuilder.Entity("DiyetisyenProje.PL.Entities.BitenListe", b =>
                {
                    b.HasOne("DiyetisyenProje.PL.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiyetisyenProje.PL.Entities.Liste", "Liste")
                        .WithMany()
                        .HasForeignKey("ListeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Liste");
                });

            modelBuilder.Entity("DiyetisyenProje.PL.Entities.ListeBesin", b =>
                {
                    b.HasOne("DiyetisyenProje.PL.Entities.Besin", "Besin")
                        .WithMany()
                        .HasForeignKey("BesinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiyetisyenProje.PL.Entities.Liste", "Liste")
                        .WithMany()
                        .HasForeignKey("ListeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Besin");

                    b.Navigation("Liste");
                });

            modelBuilder.Entity("DiyetisyenProje.PL.Entities.BesinKategori", b =>
                {
                    b.Navigation("Besinler");
                });
#pragma warning restore 612, 618
        }
    }
}
